name: setup python
description: set up a python environment
runs:
  using: composite
  steps:
    - name: install python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'
    - name: display python version
      shell: bash
      run: python -c 'import sys; print(sys.version)'
    - name: install poetry
      shell: bash
      run: python -m pip install --upgrade pip && pip install poetry yapf
    - name: cache poetry storage
      uses: actions/cache@v4.2.0
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
